# Generated by Django 6.0.5 on 2026-05-16 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='forked_from',
            field=models.ForeignKey(blank=True, help_text='The template this one was forked from, if any. SET_NULL so forks survive upstream deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='tickets.tickettemplate'),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this personal template. NULL means the template is global (visible to everyone).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tickettemplate',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_template_name_per_owner', nulls_distinct=False),
        ),
    ]
